name: 'Azure Static Web Apps Deploy'
description: 'Deploys an application to Azure Static Web Apps'
branding:
  icon: 'upload-cloud'  
  color: 'blue'
inputs:
  azure_static_web_apps_api_token:
    description: 'Required token'
    required: true
  action:
    description: 'Action to perform'
    required: true
  app_location:
    description: 'Directory location of the application source code'
    required: true
  api_location:
    description: 'Directory location of the Azure Functions source code'
    required: false
  app_artifact_location:
    description: 'Directory location of the compiled application code after building'
    required: false
outputs:
  static_web_app_url:
    description: 'Url of the application'
runs:
  using: 'docker'
  image: 'Dockerfile'